## Import libraries

In [1]:
import warnings
warnings.simplefilter(action='ignore', category=UserWarning)

import numpy as np
import pandas as pd
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import RobustScaler
from sklearn.model_selection import StratifiedKFold

from catboost import CatBoostRegressor

np.random.seed(42)

## Load source datasets

In [2]:
train = pd.read_csv("../input/mh-wsmlc/train.csv")
print(f"train: {train.shape}")
train.head()

train: (175296, 18)

,Year,Month,Day,Hour,Minute,Clearsky DHI,Clearsky DNI,Clearsky GHI,Cloud Type,Dew Point,Temperature,Pressure,Relative Humidity,Solar Zenith Angle,Precipitable Water,Wind Direction,Wind Speed,Fill Flag
0,2009,1,1,0,0,0,0,0,0,0.0,5.0,1010,75.34,106.15,0.499,346.1,3.1,0
1,2009,1,1,0,30,0,0,0,0,1.0,5.0,1010,80.81,112.28,0.490,346.1,3.1,0
2,2009,1,1,1,0,0,0,0,4,0.0,5.0,1010,78.27,118.50,0.482,347.9,3.2,0
3,2009,1,1,1,30,0,0,0,4,0.0,4.0,1010,78.27,124.78,0.478,347.9,3.1,0
4,2009,1,1,2,0,0,0,0,4,0.0,4.0,1010,76.45,131.12,0.475,350.0,3.0,0

In [3]:
test = pd.read_csv("../input/mh-wsmlc/test.csv")
print(f"test: {test.shape}")
test.head()

test: (17520, 18)

,Year,Month,Day,Hour,Minute,Cloud Type,Dew Point,Temperature,Pressure,Relative Humidity,Solar Zenith Angle,Precipitable Water,Wind Direction,Wind Speed,Fill Flag,Clearsky DHI,Clearsky DNI,Clearsky GHI
0,2019,1,1,0,0,7,18.4,18.8,1008,97.70,106.23,3.5,190,2.3,0,NaN,NaN,NaN
1,2019,1,1,0,30,3,18.4,18.6,1008,98.92,112.36,3.5,187,2.5,0,NaN,NaN,NaN
2,2019,1,1,1,0,3,18.2,18.5,1008,98.35,118.58,3.5,184,2.8,0,NaN,NaN,NaN
3,2019,1,1,1,30,3,18.2,18.3,1008,99.58,124.86,3.5,185,3.0,0,NaN,NaN,NaN
4,2019,1,1,2,0,0,18.0,18.0,1008,99.71,131.20,3.6,186,3.1,0,NaN,NaN,NaN

## Feature Engineering

In [4]:
def encode(data, col, max_val):
    data[col + '_sin'] = np.sin(2 * np.pi * data[col]/max_val)
    data[col + '_cos'] = np.cos(2 * np.pi * data[col]/max_val)
    return data

In [5]:
train['Date'] = train.apply(lambda row: pd.to_datetime(str(row['Year']).split('.')[0] + \
                                                       str(row['Month']).split('.')[0].zfill(2) + \
                                                       str(row['Day']).split('.')[0].zfill(2), format='%Y%m%d'), axis=1)

train['Quarter'] = train['Date'].apply(lambda x: pd.to_datetime(x).quarter)
train['Week'] = train['Date'].apply(lambda x: pd.to_datetime(x).week)
train['DayofWeek'] = train['Date'].apply(lambda x: pd.to_datetime(x).dayofweek)
train['isWeekend'] = np.where(train['DayofWeek'].isin([5,6]),1,0)
train['season'] = train['Month'].apply(lambda x: 0 if x in [2,3] else 1 if x in [4,5,6] else 2 if x in [7,8] else 3 if x in [9,10,11] else 4)

train.drop(['Date'], axis=1, inplace=True)
train.head()

,Year,Month,Day,Hour,Minute,Clearsky DHI,Clearsky DNI,Clearsky GHI,Cloud Type,Dew Point,...,Solar Zenith Angle,Precipitable Water,Wind Direction,Wind Speed,Fill Flag,Quarter,Week,DayofWeek,isWeekend,season
0,2009,1,1,0,0,0,0,0,0,0.0,...,106.15,0.499,346.1,3.1,0,1,1,3,0,4
1,2009,1,1,0,30,0,0,0,0,1.0,...,112.28,0.490,346.1,3.1,0,1,1,3,0,4
2,2009,1,1,1,0,0,0,0,4,0.0,...,118.50,0.482,347.9,3.2,0,1,1,3,0,4
3,2009,1,1,1,30,0,0,0,4,0.0,...,124.78,0.478,347.9,3.1,0,1,1,3,0,4
4,2009,1,1,2,0,0,0,0,4,0.0,...,131.12,0.475,350.0,3.0,0,1,1,3,0,4

In [6]:
test['Date'] = test.apply(lambda row: pd.to_datetime(str(row['Year']).split('.')[0] + \
                                                       str(row['Month']).split('.')[0].zfill(2) + \
                                                       str(row['Day']).split('.')[0].zfill(2), format='%Y%m%d'), axis=1)

test['Quarter'] = test['Date'].apply(lambda x: pd.to_datetime(x).quarter)
test['Week'] = test['Date'].apply(lambda x: pd.to_datetime(x).week)
test['DayofWeek'] = test['Date'].apply(lambda x: pd.to_datetime(x).dayofweek)
test['isWeekend'] = np.where(test['DayofWeek'].isin([5,6]),1,0)
test['season'] = test['Month'].apply(lambda x: 0 if x in [2,3] else 1 if x in [4,5,6] else 2 if x in [7,8] else 3 if x in [9,10,11] else 4)

test.drop(['Date'], axis=1, inplace=True)
test.head()

,Year,Month,Day,Hour,Minute,Cloud Type,Dew Point,Temperature,Pressure,Relative Humidity,...,Wind Speed,Fill Flag,Clearsky DHI,Clearsky DNI,Clearsky GHI,Quarter,Week,DayofWeek,isWeekend,season
0,2019,1,1,0,0,7,18.4,18.8,1008,97.70,...,2.3,0,NaN,NaN,NaN,1,1,1,0,4
1,2019,1,1,0,30,3,18.4,18.6,1008,98.92,...,2.5,0,NaN,NaN,NaN,1,1,1,0,4
2,2019,1,1,1,0,3,18.2,18.5,1008,98.35,...,2.8,0,NaN,NaN,NaN,1,1,1,0,4
3,2019,1,1,1,30,3,18.2,18.3,1008,99.58,...,3.0,0,NaN,NaN,NaN,1,1,1,0,4
4,2019,1,1,2,0,0,18.0,18.0,1008,99.71,...,3.1,0,NaN,NaN,NaN,1,1,1,0,4

In [7]:
train['Dew Point / Temperature'] = train.apply(lambda row: 0 if row['Temperature']==0 else row['Dew Point']/row['Temperature'], axis=1)
train['Dew Point / Pressure'] = train['Dew Point']/train['Pressure']
train['Precipitable Water / Dew Point'] = train.apply(lambda row: 0 if row['Dew Point']==0 else row['Precipitable Water']/row['Dew Point'], axis=1)
train['Temperature / Pressure'] = train['Temperature']/train['Pressure']
train['Humidity * Water'] = train['Relative Humidity'] * train['Precipitable Water']
train['Humidity * Wind'] = train['Relative Humidity'] * train['Wind Speed']

train = encode(train, 'Month', train['Month'].max())
train = encode(train, 'Quarter', train['Quarter'].max())
train = encode(train, 'season', train['season'].max())
train = encode(train, 'Week', train['Week'].max())
train = encode(train, 'DayofWeek', train['DayofWeek'].max())
train = encode(train, 'Day', train['Day'].max())
train = encode(train, 'Hour', train['Hour'].max())
train = encode(train, 'Solar Zenith Angle', 90)
train = encode(train, 'Wind Direction', 180)

train.drop(['Month','Quarter','season','Day',
            'Week','DayofWeek','Wind Direction'], axis=1, inplace=True)
train.head()

,Year,Hour,Minute,Clearsky DHI,Clearsky DNI,Clearsky GHI,Cloud Type,Dew Point,Temperature,Pressure,...,DayofWeek_sin,DayofWeek_cos,Day_sin,Day_cos,Hour_sin,Hour_cos,Solar Zenith Angle_sin,Solar Zenith Angle_cos,Wind Direction_sin,Wind Direction_cos
0,2009,0,0,0,0,0,0,0.0,5.0,1010,...,1.224647e-16,-1.0,0.201299,0.97953,0.000000,1.000000,0.903335,0.428935,-0.466387,0.884581
1,2009,0,30,0,0,0,0,1.0,5.0,1010,...,1.224647e-16,-1.0,0.201299,0.97953,0.000000,1.000000,0.999882,0.015358,-0.466387,0.884581
2,2009,1,0,0,0,0,4,0.0,5.0,1010,...,1.224647e-16,-1.0,0.201299,0.97953,0.269797,0.962917,0.913545,-0.406737,-0.409923,0.912120
3,2009,1,30,0,0,0,4,0.0,4.0,1010,...,1.224647e-16,-1.0,0.201299,0.97953,0.269797,0.962917,0.654477,-0.756082,-0.409923,0.912120
4,2009,2,0,0,0,0,4,0.0,4.0,1010,...,1.224647e-16,-1.0,0.201299,0.97953,0.519584,0.854419,0.267575,-0.963537,-0.342020,0.939693

In [8]:
test['Dew Point / Temperature'] = test.apply(lambda row: 0 if row['Temperature']==0 else row['Dew Point']/row['Temperature'], axis=1)
test['Dew Point / Pressure'] = test['Dew Point']/test['Pressure']
test['Precipitable Water / Dew Point'] = test.apply(lambda row: 0 if row['Dew Point']==0 else row['Precipitable Water']/row['Dew Point'], axis=1)
test['Temperature / Pressure'] = test['Temperature']/test['Pressure']
test['Humidity * Water'] = test['Relative Humidity'] * test['Precipitable Water']
test['Humidity * Wind'] = test['Relative Humidity'] * test['Wind Speed']

test = encode(test, 'Month', test['Month'].max())
test = encode(test, 'Quarter', test['Quarter'].max())
test = encode(test, 'season', test['season'].max())
test = encode(test, 'Week', test['Week'].max())
test = encode(test, 'DayofWeek', test['DayofWeek'].max())
test = encode(test, 'Day', test['Day'].max())
test = encode(test, 'Hour', test['Hour'].max())
test = encode(test, 'Solar Zenith Angle', 90)
test = encode(test, 'Wind Direction', 180)

test.drop(['Month','Quarter','season','Day',
            'Week','DayofWeek','Wind Direction'], axis=1, inplace=True)
test.head()

,Year,Hour,Minute,Cloud Type,Dew Point,Temperature,Pressure,Relative Humidity,Solar Zenith Angle,Precipitable Water,...,DayofWeek_sin,DayofWeek_cos,Day_sin,Day_cos,Hour_sin,Hour_cos,Solar Zenith Angle_sin,Solar Zenith Angle_cos,Wind Direction_sin,Wind Direction_cos
0,2019,0,0,7,18.4,18.8,1008,97.70,106.23,3.5,...,0.866025,0.5,0.201299,0.97953,0.000000,1.000000,0.905717,0.423883,0.342020,0.939693
1,2019,0,30,3,18.4,18.6,1008,98.92,112.36,3.5,...,0.866025,0.5,0.201299,0.97953,0.000000,1.000000,0.999952,0.009774,0.241922,0.970296
2,2019,1,0,3,18.2,18.5,1008,98.35,118.58,3.5,...,0.866025,0.5,0.201299,0.97953,0.269797,0.962917,0.911260,-0.411832,0.139173,0.990268
3,2019,1,30,3,18.2,18.3,1008,99.58,124.86,3.5,...,0.866025,0.5,0.201299,0.97953,0.269797,0.962917,0.650244,-0.759725,0.173648,0.984808
4,2019,2,0,0,18.0,18.0,1008,99.71,131.20,3.6,...,0.866025,0.5,0.201299,0.97953,0.519584,0.854419,0.262189,-0.965016,0.207912,0.978148

In [9]:
def shift_features(df, features, shifts):
    for feature in features:
        for shift in shifts:
            df[feature+"-"+str(shift)+"abs_shift"] = df[feature] - df[feature].shift(periods=shift, fill_value=0)
            df[feature+"+"+str(shift)+"abs_shift"] = df[feature] - df[feature].shift(periods=-shift, fill_value=0)

    df.replace(to_replace=np.inf, value=0, inplace=True)
    return df

In [10]:
features = ['Dew Point', 'Temperature', 'Pressure', 'Relative Humidity', 'Precipitable Water', 
            'Wind Speed', 'Solar Zenith Angle_sin', 'Solar Zenith Angle_cos', 'Wind Direction_sin',
            'Wind Direction_cos', 'Dew Point / Temperature', 'Dew Point / Pressure', 
            'Temperature / Pressure', 'Precipitable Water / Dew Point', 'Humidity * Water', 
            'Humidity * Wind']

shifts = [1, 2, 3, 6, 9, 12, 18, 24, 36, 48, 72]

train = shift_features(train, features, shifts)
train.head()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  after removing the cwd from sys.path.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  """

,Year,Hour,Minute,Clearsky DHI,Clearsky DNI,Clearsky GHI,Cloud Type,Dew Point,Temperature,Pressure,...,Humidity * Wind-18abs_shift,Humidity * Wind+18abs_shift,Humidity * Wind-24abs_shift,Humidity * Wind+24abs_shift,Humidity * Wind-36abs_shift,Humidity * Wind+36abs_shift,Humidity * Wind-48abs_shift,Humidity * Wind+48abs_shift,Humidity * Wind-72abs_shift,Humidity * Wind+72abs_shift
0,2009,0,0,0,0,0,0,0.0,5.0,1010,...,233.554,39.250,233.554,12.658,233.554,76.630,233.554,64.861,233.554,123.554
1,2009,0,30,0,0,0,0,1.0,5.0,1010,...,250.511,56.185,250.511,5.580,250.511,106.730,250.511,69.554,250.511,90.511
2,2009,1,0,0,0,0,4,0.0,5.0,1010,...,250.464,54.159,250.464,-31.704,250.464,106.407,250.464,65.538,250.464,40.464
3,2009,1,30,0,0,0,4,0.0,4.0,1010,...,242.637,46.263,242.637,-86.601,242.637,112.521,242.637,66.577,242.637,25.816
4,2009,2,0,0,0,0,4,0.0,4.0,1010,...,229.350,17.190,229.350,-92.586,229.350,98.570,229.350,49.790,229.350,-9.375

In [11]:
test = shift_features(test, features, shifts)
test.head()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  after removing the cwd from sys.path.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  """

,Year,Hour,Minute,Cloud Type,Dew Point,Temperature,Pressure,Relative Humidity,Solar Zenith Angle,Precipitable Water,...,Humidity * Wind-18abs_shift,Humidity * Wind+18abs_shift,Humidity * Wind-24abs_shift,Humidity * Wind+24abs_shift,Humidity * Wind-36abs_shift,Humidity * Wind+36abs_shift,Humidity * Wind-48abs_shift,Humidity * Wind+48abs_shift,Humidity * Wind-72abs_shift,Humidity * Wind+72abs_shift
0,2019,0,0,7,18.4,18.8,1008,97.70,106.23,3.5,...,224.710,-93.786,224.710,-44.264,224.710,-117.810,224.710,104.710,224.710,165.382
1,2019,0,30,3,18.4,18.6,1008,98.92,112.36,3.5,...,247.300,-67.196,247.300,-23.040,247.300,-86.657,247.300,137.300,247.300,180.254
2,2019,1,0,3,18.2,18.5,1008,98.35,118.58,3.5,...,275.380,-41.580,275.380,-11.198,275.380,-48.532,275.380,165.380,275.380,187.486
3,2019,1,30,3,18.2,18.3,1008,99.58,124.86,3.5,...,298.740,-8.625,298.740,16.650,298.740,-11.796,298.740,188.740,298.740,195.956
4,2019,2,0,0,18.0,18.0,1008,99.71,131.20,3.6,...,309.101,10.031,309.101,18.611,309.101,18.767,309.101,209.101,309.101,194.369

In [12]:
features = test.columns.tolist()
features.remove('Clearsky DHI')
features.remove('Clearsky DNI')
features.remove('Clearsky GHI')
features.remove('Hour')
features.remove('Solar Zenith Angle')
len(features)

387

In [13]:
cat_cols = ['Year','Minute','isWeekend','Pressure','Fill Flag','Cloud Type']

train[cat_cols] = train[cat_cols].astype(int)
test[cat_cols] = test[cat_cols].astype(int)
cat_cols_indices = [train[features].columns.get_loc(col) for col in cat_cols]
print(cat_cols_indices)

[0, 1, 10, 5, 9, 2]

In [14]:
num_cols = [col for col in features if col not in cat_cols]

scaler = RobustScaler().fit(train[num_cols])
train[num_cols] = scaler.transform(train[num_cols])
test[num_cols] = scaler.transform(test[num_cols])

In [15]:
train_org = train.copy()
train = train[train['Solar Zenith Angle']<93].reset_index(drop=True).copy()
train = train[~train['Hour'].isin([1,2,3,4,5,6,7,8,9])].reset_index(drop=True).copy()
print(f"train_org: {train_org.shape} \ntrain: {train.shape}")

train_org: (175296, 392)
train: (91563, 392)

In [16]:
test_org = test.copy()
test = test[test['Solar Zenith Angle']<93].reset_index(drop=True).copy()
test = test[~test['Hour'].isin([1,2,3,4,5,6,7,8,9])].reset_index(drop=True).copy()
print(f"test_org: {test_org.shape} \ntest: {test.shape}")

test_org: (17520, 392)
test: (9150, 392)

## CatBoost

In [17]:
dhi_model = CatBoostRegressor(
    objective='RMSE',
    eval_metric='RMSE',
    num_boost_round=5000,
    learning_rate=0.067,
    reg_lambda=0.1724,
    use_best_model=True,
    bootstrap_type='Poisson',
    subsample=0.6654,
    max_depth=11, 
    grow_policy='Lossguide',
    min_data_in_leaf=14, 
    max_leaves=117,
    task_type='GPU',
    verbose=0,
    random_state=42
)

dni_model = CatBoostRegressor(
    objective='RMSE',
    eval_metric='RMSE',
    num_boost_round=5000,
    learning_rate=0.0656,
    reg_lambda=0.0013,
    use_best_model=True,
    bootstrap_type='Poisson',
    subsample=0.92993,
    max_depth=12, 
    grow_policy='Lossguide',
    min_data_in_leaf=8, 
    max_leaves=68,
    task_type='GPU',
    verbose=0,
    random_state=42
)

ghi_model = CatBoostRegressor(
    objective='RMSE',
    eval_metric='RMSE',
    num_boost_round=5000,
    learning_rate=0.05,
    reg_lambda=0.044,
    use_best_model=True,
    bootstrap_type='Poisson',
    subsample=0.9947,
    max_depth=7, 
    grow_policy='Lossguide',
    min_data_in_leaf=9, 
    max_leaves=153,
    task_type='GPU',
    verbose=0,
    random_state=42
)

model_dict = {
    'Clearsky DHI': dhi_model,
    'Clearsky DNI': dni_model,
    'Clearsky GHI': ghi_model
}

In [18]:
for target in ['Clearsky DHI','Clearsky DNI','Clearsky GHI']:
    print(f"Training for target: {target}\n")
    
    splits = 10
    skf = StratifiedKFold(n_splits=splits, shuffle=True, random_state=42)
    oof_preds = np.zeros((train.shape[0],))
    model_preds = 0
    
    for fold, (train_idx, valid_idx) in enumerate(skf.split(train[features], train['Year'])):
        X_train, X_valid = train.loc[train_idx][features], train.loc[valid_idx][features]
        y_train, y_valid = train.loc[train_idx][target], train.loc[valid_idx][target]
        
        model = model_dict.get(target)
        
        model.fit(X_train, y_train, eval_set=[(X_valid, y_valid)], 
                  cat_features=cat_cols_indices,
                  early_stopping_rounds=50, verbose=1000)
        
        model_preds += model.predict(test[features]) / splits
        oof_preds[valid_idx] = model.predict(X_valid)
        
        print(f"\nFold-{fold+1} | MSE: {mean_squared_error(y_valid, oof_preds[valid_idx])}\n")
    
    train[target+'_cb'] = oof_preds
    test[target+'_cb'] = model_preds
    
    model_mse = mean_squared_error(train[target], oof_preds)
    print(f"All Folds | MSE: {model_mse}\n")

Training for target: Clearsky DHI

0:	learn: 51.3816351	test: 51.2728261	best: 51.2728261 (0)	total: 73.3ms	remaining: 6m 6s
1000:	learn: 3.3679923	test: 7.9897520	best: 7.9897520 (1000)	total: 1m 7s	remaining: 4m 31s
2000:	learn: 1.9170653	test: 7.2487993	best: 7.2487993 (2000)	total: 2m 15s	remaining: 3m 22s
3000:	learn: 1.3794789	test: 7.0400673	best: 7.0400673 (3000)	total: 3m 22s	remaining: 2m 14s
4000:	learn: 1.0923750	test: 6.9559067	best: 6.9558767 (3997)	total: 4m 29s	remaining: 1m 7s
4999:	learn: 0.9159456	test: 6.9129110	best: 6.9129110 (4999)	total: 5m 36s	remaining: 0us
bestTest = 6.912910976
bestIteration = 4999

Fold-1 | MSE: 47.788494131942585

0:	learn: 51.4028278	test: 51.2678185	best: 51.2678185 (0)	total: 67.3ms	remaining: 5m 36s
1000:	learn: 3.3616079	test: 8.0949876	best: 8.0949876 (1000)	total: 1m 7s	remaining: 4m 31s
2000:	learn: 1.8482869	test: 7.3219231	best: 7.3219231 (2000)	total: 2m 16s	remaining: 3m 23s
3000:	learn: 1.3001525	test: 7.1146057	best: 7.1146057 (3000)	total: 3m 24s	remaining: 2m 16s
4000:	learn: 1.0200321	test: 7.0251087	best: 7.0251087 (4000)	total: 4m 31s	remaining: 1m 7s
4999:	learn: 0.8492516	test: 6.9832414	best: 6.9832414 (4999)	total: 5m 38s	remaining: 0us
bestTest = 6.983241427
bestIteration = 4999

Fold-2 | MSE: 48.76574715818261

0:	learn: 51.3522276	test: 51.8054171	best: 51.8054171 (0)	total: 65.5ms	remaining: 5m 27s
1000:	learn: 3.3803151	test: 8.2499897	best: 8.2499897 (1000)	total: 1m 7s	remaining: 4m 31s
2000:	learn: 1.8955924	test: 7.4630199	best: 7.4630199 (2000)	total: 2m 15s	remaining: 3m 23s
3000:	learn: 1.3458851	test: 7.2331476	best: 7.2331476 (3000)	total: 3m 23s	remaining: 2m 15s
4000:	learn: 1.0624925	test: 7.1394397	best: 7.1394318 (3999)	total: 4m 31s	remaining: 1m 7s
4999:	learn: 0.8884162	test: 7.0918248	best: 7.0918248 (4999)	total: 5m 39s	remaining: 0us
bestTest = 7.091824824
bestIteration = 4999

Fold-3 | MSE: 50.29381587731336

0:	learn: 51.3511013	test: 51.7677080	best: 51.7677080 (0)	total: 70.2ms	remaining: 5m 50s
1000:	learn: 3.4006333	test: 7.8121224	best: 7.8121224 (1000)	total: 1m 8s	remaining: 4m 32s
2000:	learn: 1.9097703	test: 7.0430616	best: 7.0430616 (2000)	total: 2m 16s	remaining: 3m 25s
3000:	learn: 1.3501028	test: 6.8328414	best: 6.8328414 (3000)	total: 3m 24s	remaining: 2m 16s
4000:	learn: 1.0551313	test: 6.7478257	best: 6.7478257 (4000)	total: 4m 32s	remaining: 1m 8s
4999:	learn: 0.8727119	test: 6.7066626	best: 6.7066606 (4998)	total: 5m 39s	remaining: 0us
bestTest = 6.706660597
bestIteration = 4998
Shrink model to first 4999 iterations.

Fold-4 | MSE: 44.97938319968666

0:	learn: 51.3289625	test: 51.8636621	best: 51.8636621 (0)	total: 70.1ms	remaining: 5m 50s
1000:	learn: 3.5547938	test: 8.1494721	best: 8.1494721 (1000)	total: 1m 7s	remaining: 4m 31s
2000:	learn: 2.1252015	test: 7.4171877	best: 7.4171877 (2000)	total: 2m 15s	remaining: 3m 23s
3000:	learn: 1.5840344	test: 7.2020828	best: 7.2020828 (3000)	total: 3m 23s	remaining: 2m 15s
4000:	learn: 1.2914940	test: 7.1201298	best: 7.1201298 (4000)	total: 4m 31s	remaining: 1m 7s
4999:	learn: 1.1068402	test: 7.0758616	best: 7.0758411 (4998)	total: 5m 39s	remaining: 0us
bestTest = 7.075841112
bestIteration = 4998
Shrink model to first 4999 iterations.

Fold-5 | MSE: 50.067557976637374

0:	learn: 51.3854741	test: 51.2136391	best: 51.2136391 (0)	total: 66ms	remaining: 5m 29s
1000:	learn: 3.1933623	test: 8.1273991	best: 8.1273991 (1000)	total: 1m 8s	remaining: 4m 32s
2000:	learn: 1.7233338	test: 7.3901768	best: 7.3901768 (2000)	total: 2m 15s	remaining: 3m 23s
3000:	learn: 1.1885282	test: 7.1999928	best: 7.1999928 (3000)	total: 3m 23s	remaining: 2m 15s
4000:	learn: 0.9199528	test: 7.1204622	best: 7.1204622 (4000)	total: 4m 31s	remaining: 1m 7s
4999:	learn: 0.7614797	test: 7.0834356	best: 7.0833973 (4998)	total: 5m 39s	remaining: 0us
bestTest = 7.083397258
bestIteration = 4998
Shrink model to first 4999 iterations.

Fold-6 | MSE: 50.174643424227455

0:	learn: 51.3383785	test: 51.7008293	best: 51.7008293 (0)	total: 66.5ms	remaining: 5m 32s
1000:	learn: 3.2935775	test: 7.9822221	best: 7.9822221 (1000)	total: 1m 9s	remaining: 4m 35s
2000:	learn: 1.8402471	test: 7.2390898	best: 7.2390898 (2000)	total: 2m 16s	remaining: 3m 24s
3000:	learn: 1.2929886	test: 7.0372973	best: 7.0372973 (3000)	total: 3m 24s	remaining: 2m 16s
4000:	learn: 1.0052221	test: 6.9536169	best: 6.9536169 (4000)	total: 4m 32s	remaining: 1m 7s
4999:	learn: 0.8302818	test: 6.9115813	best: 6.9115813 (4999)	total: 5m 39s	remaining: 0us
bestTest = 6.911581308
bestIteration = 4999

Fold-7 | MSE: 47.77015977398053

0:	learn: 51.3733136	test: 51.4703085	best: 51.4703085 (0)	total: 66.5ms	remaining: 5m 32s
1000:	learn: 3.4180902	test: 8.0293646	best: 8.0293646 (1000)	total: 1m 8s	remaining: 4m 31s
2000:	learn: 1.9796418	test: 7.2958944	best: 7.2958944 (2000)	total: 2m 16s	remaining: 3m 24s
3000:	learn: 1.4406964	test: 7.0868801	best: 7.0868801 (3000)	total: 3m 24s	remaining: 2m 16s
4000:	learn: 1.1582137	test: 7.0030506	best: 7.0030506 (4000)	total: 4m 33s	remaining: 1m 8s
4999:	learn: 0.9824493	test: 6.9635129	best: 6.9635129 (4999)	total: 5m 42s	remaining: 0us
bestTest = 6.963512884
bestIteration = 4999

Fold-8 | MSE: 48.49016755794741

0:	learn: 51.4667904	test: 50.4781225	best: 50.4781225 (0)	total: 67.5ms	remaining: 5m 37s
1000:	learn: 3.3792373	test: 8.1384491	best: 8.1384491 (1000)	total: 1m 8s	remaining: 4m 34s
2000:	learn: 1.9278131	test: 7.3980128	best: 7.3980128 (2000)	total: 2m 16s	remaining: 3m 23s
3000:	learn: 1.3848369	test: 7.1795687	best: 7.1795525 (2999)	total: 3m 23s	remaining: 2m 15s
4000:	learn: 1.0999378	test: 7.0900171	best: 7.0900171 (4000)	total: 4m 31s	remaining: 1m 7s
4999:	learn: 0.9220514	test: 7.0451756	best: 7.0451756 (4999)	total: 5m 40s	remaining: 0us
bestTest = 7.045175552
bestIteration = 4999

Fold-9 | MSE: 49.6344625497776

0:	learn: 51.4133592	test: 51.2164924	best: 51.2164924 (0)	total: 65.8ms	remaining: 5m 29s
1000:	learn: 3.3952196	test: 7.8790907	best: 7.8790907 (1000)	total: 1m 8s	remaining: 4m 33s
2000:	learn: 1.9698303	test: 7.1503290	best: 7.1503290 (2000)	total: 2m 18s	remaining: 3m 26s
3000:	learn: 1.4367591	test: 6.9357094	best: 6.9357094 (3000)	total: 3m 25s	remaining: 2m 16s
4000:	learn: 1.1533277	test: 6.8518507	best: 6.8518507 (4000)	total: 4m 32s	remaining: 1m 8s
4999:	learn: 0.9775491	test: 6.8093644	best: 6.8093644 (4999)	total: 5m 39s	remaining: 0us
bestTest = 6.809364396
bestIteration = 4999

Fold-10 | MSE: 46.36741225894386

All Folds | MSE: 48.43320130276061

Training for target: Clearsky DNI

0:	learn: 250.6298258	test: 251.0740027	best: 251.0740027 (0)	total: 48ms	remaining: 3m 59s
1000:	learn: 14.0128694	test: 25.7659894	best: 25.7659894 (1000)	total: 43.5s	remaining: 2m 53s
2000:	learn: 7.9153019	test: 22.7561224	best: 22.7561224 (2000)	total: 1m 28s	remaining: 2m 12s
3000:	learn: 5.3994348	test: 21.7336347	best: 21.7336347 (3000)	total: 2m 11s	remaining: 1m 27s
4000:	learn: 4.1400804	test: 21.3076025	best: 21.3076025 (4000)	total: 2m 54s	remaining: 43.5s
4999:	learn: 3.4071589	test: 21.0874551	best: 21.0874551 (4999)	total: 3m 37s	remaining: 0us
bestTest = 21.08745512
bestIteration = 4999

Fold-1 | MSE: 444.68091009538483

0:	learn: 250.6942965	test: 250.5117584	best: 250.5117584 (0)	total: 48ms	remaining: 4m
1000:	learn: 13.8967898	test: 24.6198120	best: 24.6198120 (1000)	total: 44.1s	remaining: 2m 56s
2000:	learn: 7.6670698	test: 21.5432079	best: 21.5432079 (2000)	total: 1m 27s	remaining: 2m 10s
3000:	learn: 5.1028375	test: 20.5360802	best: 20.5360802 (3000)	total: 2m 11s	remaining: 1m 27s
4000:	learn: 3.7942516	test: 20.0955917	best: 20.0955917 (4000)	total: 2m 54s	remaining: 43.5s
4999:	learn: 3.0123511	test: 19.8869642	best: 19.8869004 (4998)	total: 3m 36s	remaining: 0us
bestTest = 19.88690037
bestIteration = 4998
Shrink model to first 4999 iterations.

Fold-2 | MSE: 395.4886221292233

0:	learn: 250.5682768	test: 251.5057895	best: 251.5057895 (0)	total: 45.6ms	remaining: 3m 47s
1000:	learn: 13.8260176	test: 25.9631683	best: 25.9631683 (1000)	total: 43.8s	remaining: 2m 54s
2000:	learn: 7.4269861	test: 22.8155317	best: 22.8155317 (2000)	total: 1m 27s	remaining: 2m 10s
3000:	learn: 4.7569456	test: 21.7189211	best: 21.7189211 (3000)	total: 2m 10s	remaining: 1m 26s
4000:	learn: 3.3757094	test: 21.2614217	best: 21.2614217 (4000)	total: 2m 52s	remaining: 43.2s
4999:	learn: 2.5804675	test: 21.0367787	best: 21.0367787 (4999)	total: 3m 35s	remaining: 0us
bestTest = 21.03677869
bestIteration = 4999

Fold-3 | MSE: 442.54581816237095

0:	learn: 250.4449907	test: 252.7222447	best: 252.7222447 (0)	total: 48.5ms	remaining: 4m 2s
1000:	learn: 13.8256204	test: 24.6165348	best: 24.6164860 (999)	total: 44.7s	remaining: 2m 58s
2000:	learn: 7.7192310	test: 21.6060962	best: 21.6060962 (2000)	total: 1m 28s	remaining: 2m 11s
3000:	learn: 5.2208093	test: 20.6228888	best: 20.6228888 (3000)	total: 2m 11s	remaining: 1m 27s
4000:	learn: 3.9204327	test: 20.1987334	best: 20.1987334 (4000)	total: 2m 55s	remaining: 43.8s
4999:	learn: 3.1645284	test: 19.9893860	best: 19.9893860 (4999)	total: 3m 39s	remaining: 0us
bestTest = 19.98938597
bestIteration = 4999

Fold-4 | MSE: 399.57572491597665

0:	learn: 250.7507499	test: 249.9539285	best: 249.9539285 (0)	total: 46.9ms	remaining: 3m 54s
1000:	learn: 13.9805208	test: 25.9374458	best: 25.9374458 (1000)	total: 44s	remaining: 2m 55s
2000:	learn: 7.7174478	test: 22.8326772	best: 22.8326772 (2000)	total: 1m 28s	remaining: 2m 11s
3000:	learn: 5.1836686	test: 21.7947966	best: 21.7947966 (3000)	total: 2m 11s	remaining: 1m 27s
4000:	learn: 3.8740144	test: 21.3591382	best: 21.3591382 (4000)	total: 2m 53s	remaining: 43.4s
4999:	learn: 3.1156198	test: 21.1536175	best: 21.1536175 (4999)	total: 3m 37s	remaining: 0us
bestTest = 21.15361754
bestIteration = 4999

Fold-5 | MSE: 447.4777666247311

0:	learn: 250.7629775	test: 249.7851309	best: 249.7851309 (0)	total: 45.8ms	remaining: 3m 49s
1000:	learn: 13.8380217	test: 25.0311067	best: 25.0311067 (1000)	total: 44.2s	remaining: 2m 56s
2000:	learn: 7.6623303	test: 21.8829420	best: 21.8829420 (2000)	total: 1m 27s	remaining: 2m 11s
3000:	learn: 5.1368937	test: 20.8570450	best: 20.8570450 (3000)	total: 2m 12s	remaining: 1m 28s
4000:	learn: 3.8421431	test: 20.4237960	best: 20.4235915 (3999)	total: 2m 55s	remaining: 43.9s
4999:	learn: 3.0579756	test: 20.2215517	best: 20.2215517 (4999)	total: 3m 38s	remaining: 0us
bestTest = 20.22155165
bestIteration = 4999

Fold-6 | MSE: 408.9096068859154

0:	learn: 250.5878198	test: 251.3613159	best: 251.3613159 (0)	total: 45.7ms	remaining: 3m 48s
1000:	learn: 14.3865368	test: 25.3627451	best: 25.3627451 (1000)	total: 43.4s	remaining: 2m 53s
2000:	learn: 8.3686465	test: 22.2660462	best: 22.2660462 (2000)	total: 1m 26s	remaining: 2m 9s
3000:	learn: 5.9667760	test: 21.2389590	best: 21.2389590 (3000)	total: 2m 10s	remaining: 1m 26s
4000:	learn: 4.7587510	test: 20.7988032	best: 20.7988032 (4000)	total: 2m 52s	remaining: 43.1s
4999:	learn: 4.0695368	test: 20.5924510	best: 20.5924510 (4999)	total: 3m 35s	remaining: 0us
bestTest = 20.59245102
bestIteration = 4999

Fold-7 | MSE: 424.0503331068987

0:	learn: 250.5585488	test: 251.6341766	best: 251.6341766 (0)	total: 48.1ms	remaining: 4m
1000:	learn: 13.8656982	test: 25.3922902	best: 25.3922902 (1000)	total: 44.5s	remaining: 2m 57s
2000:	learn: 7.6911798	test: 22.3251825	best: 22.3251825 (2000)	total: 1m 27s	remaining: 2m 11s
3000:	learn: 5.1568597	test: 21.3096540	best: 21.3096540 (3000)	total: 2m 10s	remaining: 1m 26s
4000:	learn: 3.8538391	test: 20.8774960	best: 20.8774960 (4000)	total: 2m 53s	remaining: 43.2s
4999:	learn: 3.1034934	test: 20.6667457	best: 20.6667457 (4999)	total: 3m 35s	remaining: 0us
bestTest = 20.66674572
bestIteration = 4999

Fold-8 | MSE: 427.1156057604129

0:	learn: 250.9307460	test: 248.2384879	best: 248.2384879 (0)	total: 45.4ms	remaining: 3m 46s
1000:	learn: 14.0537553	test: 25.2006409	best: 25.2006409 (1000)	total: 43.5s	remaining: 2m 53s
2000:	learn: 7.9590450	test: 22.1894839	best: 22.1894839 (2000)	total: 1m 27s	remaining: 2m 11s
3000:	learn: 5.5198563	test: 21.1785509	best: 21.1785509 (3000)	total: 2m 10s	remaining: 1m 26s
4000:	learn: 4.3058656	test: 20.7657970	best: 20.7657970 (4000)	total: 2m 53s	remaining: 43.2s
4999:	learn: 3.5941605	test: 20.5608772	best: 20.5608772 (4999)	total: 3m 36s	remaining: 0us
bestTest = 20.56087723
bestIteration = 4999

Fold-9 | MSE: 422.7493518205602

0:	learn: 250.7353624	test: 250.0407027	best: 250.0407027 (0)	total: 47.9ms	remaining: 3m 59s
1000:	learn: 14.3291316	test: 24.9106255	best: 24.9106255 (1000)	total: 43.8s	remaining: 2m 55s
2000:	learn: 8.2923532	test: 21.8483057	best: 21.8483057 (2000)	total: 1m 27s	remaining: 2m 10s
3000:	learn: 5.8958946	test: 20.8836688	best: 20.8836688 (3000)	total: 2m 9s	remaining: 1m 26s
4000:	learn: 4.6546383	test: 20.4558484	best: 20.4558484 (4000)	total: 2m 51s	remaining: 42.9s
4999:	learn: 3.9457650	test: 20.2435787	best: 20.2435787 (4999)	total: 3m 34s	remaining: 0us
bestTest = 20.24357872
bestIteration = 4999

Fold-10 | MSE: 409.8023091383891

All Folds | MSE: 422.2397795692253

Training for target: Clearsky GHI

0:	learn: 288.5754134	test: 289.8160861	best: 289.8160861 (0)	total: 60.1ms	remaining: 5m
1000:	learn: 2.6180291	test: 4.8017252	best: 4.8017252 (1000)	total: 52.1s	remaining: 3m 28s
2000:	learn: 1.3828988	test: 4.1990633	best: 4.1990633 (2000)	total: 1m 43s	remaining: 2m 35s
3000:	learn: 0.8641928	test: 4.0146703	best: 4.0146703 (3000)	total: 2m 33s	remaining: 1m 42s
4000:	learn: 0.5788375	test: 3.9412675	best: 3.9412675 (4000)	total: 3m 22s	remaining: 50.7s
4999:	learn: 0.4025612	test: 3.9051666	best: 3.9051666 (4999)	total: 4m 11s	remaining: 0us
bestTest = 3.905166566
bestIteration = 4999

Fold-1 | MSE: 15.250206709434188

0:	learn: 288.8912313	test: 286.9658425	best: 286.9658425 (0)	total: 63.2ms	remaining: 5m 16s
1000:	learn: 2.6075357	test: 4.9248572	best: 4.9248572 (1000)	total: 51.7s	remaining: 3m 26s
2000:	learn: 1.3809111	test: 4.3231366	best: 4.3231366 (2000)	total: 1m 43s	remaining: 2m 34s
3000:	learn: 0.8636870	test: 4.1416544	best: 4.1416544 (3000)	total: 2m 32s	remaining: 1m 41s
4000:	learn: 0.5760145	test: 4.0681506	best: 4.0681506 (4000)	total: 3m 22s	remaining: 50.5s
4999:	learn: 0.4003646	test: 4.0327885	best: 4.0327885 (4999)	total: 4m 12s	remaining: 0us
bestTest = 4.032788472
bestIteration = 4999

Fold-2 | MSE: 16.26319678916342

0:	learn: 288.6796985	test: 288.8653714	best: 288.8653714 (0)	total: 64ms	remaining: 5m 20s
1000:	learn: 2.6346144	test: 4.8995021	best: 4.8995021 (1000)	total: 52.5s	remaining: 3m 29s
2000:	learn: 1.4340098	test: 4.2883751	best: 4.2883751 (2000)	total: 1m 43s	remaining: 2m 35s
3000:	learn: 0.9130727	test: 4.0934064	best: 4.0934064 (3000)	total: 2m 33s	remaining: 1m 42s
4000:	learn: 0.6246419	test: 4.0127627	best: 4.0127597 (3999)	total: 3m 22s	remaining: 50.7s
4999:	learn: 0.4464834	test: 3.9739751	best: 3.9739751 (4999)	total: 4m 13s	remaining: 0us
bestTest = 3.973975056
bestIteration = 4999

Fold-3 | MSE: 15.792360056534497

0:	learn: 288.4952387	test: 290.5169614	best: 290.5169614 (0)	total: 59.6ms	remaining: 4m 57s
1000:	learn: 2.6138835	test: 4.7627565	best: 4.7627565 (1000)	total: 53.4s	remaining: 3m 33s
2000:	learn: 1.3976132	test: 4.1501467	best: 4.1501467 (2000)	total: 1m 46s	remaining: 2m 38s
3000:	learn: 0.8771884	test: 3.9667326	best: 3.9667326 (3000)	total: 2m 37s	remaining: 1m 45s
4000:	learn: 0.5870737	test: 3.8864464	best: 3.8864464 (4000)	total: 3m 27s	remaining: 51.8s
4999:	learn: 0.4078290	test: 3.8493063	best: 3.8492967 (4997)	total: 4m 17s	remaining: 0us
bestTest = 3.849296747
bestIteration = 4997
Shrink model to first 4998 iterations.

Fold-4 | MSE: 14.817079870892986

0:	learn: 288.7253786	test: 288.4567637	best: 288.4567637 (0)	total: 64.3ms	remaining: 5m 21s
1000:	learn: 2.6365151	test: 4.8985811	best: 4.8985811 (1000)	total: 53.1s	remaining: 3m 32s
2000:	learn: 1.4149664	test: 4.2881154	best: 4.2881154 (2000)	total: 1m 45s	remaining: 2m 37s
3000:	learn: 0.8888838	test: 4.0940563	best: 4.0940563 (3000)	total: 2m 34s	remaining: 1m 43s
4000:	learn: 0.5974535	test: 4.0150189	best: 4.0150189 (4000)	total: 3m 24s	remaining: 51.1s
4999:	learn: 0.4209999	test: 3.9748754	best: 3.9748754 (4999)	total: 4m 13s	remaining: 0us
bestTest = 3.974875402
bestIteration = 4999

Fold-5 | MSE: 15.79971955219115

0:	learn: 288.7118321	test: 288.5741813	best: 288.5741813 (0)	total: 59ms	remaining: 4m 54s
1000:	learn: 2.5883710	test: 4.7544121	best: 4.7544121 (1000)	total: 52.7s	remaining: 3m 30s
2000:	learn: 1.3909067	test: 4.1659942	best: 4.1659942 (2000)	total: 1m 43s	remaining: 2m 34s
3000:	learn: 0.8653048	test: 3.9695404	best: 3.9695404 (3000)	total: 2m 32s	remaining: 1m 41s
4000:	learn: 0.5739280	test: 3.8950011	best: 3.8950011 (4000)	total: 3m 23s	remaining: 50.9s
4999:	learn: 0.3986120	test: 3.8584341	best: 3.8584341 (4999)	total: 4m 12s	remaining: 0us
bestTest = 3.858434138
bestIteration = 4999

Fold-6 | MSE: 14.887485468752761

0:	learn: 288.7020404	test: 288.6669865	best: 288.6669865 (0)	total: 59.3ms	remaining: 4m 56s
1000:	learn: 2.6114670	test: 4.8116576	best: 4.8116576 (1000)	total: 52.5s	remaining: 3m 29s
2000:	learn: 1.4038059	test: 4.2060494	best: 4.2060494 (2000)	total: 1m 42s	remaining: 2m 33s
3000:	learn: 0.8751457	test: 4.0077674	best: 4.0077178 (2999)	total: 2m 32s	remaining: 1m 41s
4000:	learn: 0.5822143	test: 3.9254239	best: 3.9254239 (4000)	total: 3m 22s	remaining: 50.6s
4999:	learn: 0.4055489	test: 3.8859005	best: 3.8859005 (4999)	total: 4m 12s	remaining: 0us
bestTest = 3.885900523
bestIteration = 4999

Fold-7 | MSE: 15.100103161718406

0:	learn: 288.7030088	test: 288.6572157	best: 288.6572157 (0)	total: 59.2ms	remaining: 4m 56s
1000:	learn: 2.6606544	test: 4.6936249	best: 4.6936249 (1000)	total: 52s	remaining: 3m 27s
2000:	learn: 1.4697000	test: 4.0913260	best: 4.0913260 (2000)	total: 1m 42s	remaining: 2m 33s
3000:	learn: 0.9555931	test: 3.8983113	best: 3.8983113 (3000)	total: 2m 32s	remaining: 1m 41s
4000:	learn: 0.6753161	test: 3.8191534	best: 3.8191513 (3999)	total: 3m 21s	remaining: 50.4s
4999:	learn: 0.5032220	test: 3.7804523	best: 3.7804523 (4999)	total: 4m 11s	remaining: 0us
bestTest = 3.780452275
bestIteration = 4999

Fold-8 | MSE: 14.291892305233546

0:	learn: 288.8765419	test: 287.0862160	best: 287.0862160 (0)	total: 63.9ms	remaining: 5m 19s
1000:	learn: 2.6355935	test: 4.7022231	best: 4.7022231 (1000)	total: 52.7s	remaining: 3m 30s
2000:	learn: 1.4205460	test: 4.1172486	best: 4.1172486 (2000)	total: 1m 42s	remaining: 2m 34s
3000:	learn: 0.8924718	test: 3.9357341	best: 3.9357341 (3000)	total: 2m 32s	remaining: 1m 41s
4000:	learn: 0.5967648	test: 3.8569502	best: 3.8569502 (4000)	total: 3m 21s	remaining: 50.4s
4999:	learn: 0.4134009	test: 3.8185454	best: 3.8185454 (4999)	total: 4m 12s	remaining: 0us
bestTest = 3.818545392
bestIteration = 4999

Fold-9 | MSE: 14.581214890529264

0:	learn: 288.6225859	test: 289.3763650	best: 289.3763650 (0)	total: 63.6ms	remaining: 5m 18s
1000:	learn: 2.6429124	test: 4.7303793	best: 4.7303793 (1000)	total: 51.7s	remaining: 3m 26s
2000:	learn: 1.4321209	test: 4.1488263	best: 4.1488263 (2000)	total: 1m 42s	remaining: 2m 33s
3000:	learn: 0.9002440	test: 3.9588797	best: 3.9588797 (3000)	total: 2m 31s	remaining: 1m 41s
4000:	learn: 0.6095607	test: 3.8815737	best: 3.8815737 (4000)	total: 3m 21s	remaining: 50.4s
4999:	learn: 0.4317506	test: 3.8441340	best: 3.8441340 (4999)	total: 4m 10s	remaining: 0us
bestTest = 3.844133964
bestIteration = 4999

Fold-10 | MSE: 14.777393030889414

All Folds | MSE: 15.156085252426465

In [19]:
Xtrain = pd.merge(
    train_org, 
    train,
    how='left',
    on=features,
    sort=False
)

print(f"Xtrain: {Xtrain.shape}")
Xtrain.head()

Xtrain: (175296, 400)

,Year,Hour_x,Minute,Clearsky DHI_x,Clearsky DNI_x,Clearsky GHI_x,Cloud Type,Dew Point,Temperature,Pressure,...,Humidity * Wind-72abs_shift,Humidity * Wind+72abs_shift,Hour_y,Clearsky DHI_y,Clearsky DNI_y,Clearsky GHI_y,Solar Zenith Angle_y,Clearsky DHI_cb,Clearsky DNI_cb,Clearsky GHI_cb
0,2009,0,0,0,0,0,0,-1.153846,-1.153846,1010,...,1.449289,0.765293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2009,0,30,0,0,0,0,-1.076923,-1.153846,1010,...,1.554479,0.560281,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2009,1,0,0,0,0,4,-1.153846,-1.153846,1010,...,1.554188,0.249770,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2009,1,30,0,0,0,4,-1.153846,-1.230769,1010,...,1.505634,0.158888,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2009,2,0,0,0,0,4,-1.153846,-1.230769,1010,...,1.423210,-0.059450,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
Xtest = pd.merge(
    test_org, 
    test,
    how='left',
    on=features,
    sort=False
)

print(f"Xtest: {Xtest.shape}")
Xtest.head()

Xtest: (17520, 400)

,Year,Hour_x,Minute,Cloud Type,Dew Point,Temperature,Pressure,Relative Humidity,Solar Zenith Angle_x,Precipitable Water,...,Humidity * Wind-72abs_shift,Humidity * Wind+72abs_shift,Hour_y,Solar Zenith Angle_y,Clearsky DHI_y,Clearsky DNI_y,Clearsky GHI_y,Clearsky DHI_cb,Clearsky DNI_cb,Clearsky GHI_cb
0,2019,0,0,7,0.261538,-0.092308,1008,0.416255,106.23,0.235775,...,1.394427,1.024810,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019,0,30,3,0.261538,-0.107692,1008,0.453956,112.36,0.235775,...,1.534560,1.117081,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2019,1,0,3,0.246154,-0.115385,1008,0.436341,118.58,0.235775,...,1.708750,1.161952,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019,1,30,3,0.246154,-0.130769,1008,0.474351,124.86,0.235775,...,1.853660,1.214503,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019,2,0,0,0.230769,-0.153846,1008,0.478368,131.20,0.272964,...,1.917933,1.204656,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
Xtrain['Clearsky DHI_cb'] = Xtrain.apply(lambda row: 0 if row['Solar Zenith Angle_x']>=93 or row['Hour_x'] in [1,2,3,4,5,6,7,8,9] else row['Clearsky DHI_cb'], axis=1)
Xtrain['Clearsky DNI_cb'] = Xtrain.apply(lambda row: 0 if row['Solar Zenith Angle_x']>=93 or row['Hour_x'] in [1,2,3,4,5,6,7,8,9] else row['Clearsky DNI_cb'], axis=1)
Xtrain['Clearsky GHI_cb'] = Xtrain.apply(lambda row: 0 if row['Solar Zenith Angle_x']>=93 or row['Hour_x'] in [1,2,3,4,5,6,7,8,9] else row['Clearsky GHI_cb'], axis=1)

Xtrain['Clearsky DNI_cb'] = Xtrain.apply(lambda row: 0 if row['Clearsky DHI_cb']==0 else row['Clearsky DNI_cb'], axis=1)
Xtrain['Clearsky GHI_cb'] = Xtrain.apply(lambda row: 0 if row['Clearsky DHI_cb']==0 else row['Clearsky GHI_cb'], axis=1)

Xtrain.head()

,Year,Hour_x,Minute,Clearsky DHI_x,Clearsky DNI_x,Clearsky GHI_x,Cloud Type,Dew Point,Temperature,Pressure,...,Humidity * Wind-72abs_shift,Humidity * Wind+72abs_shift,Hour_y,Clearsky DHI_y,Clearsky DNI_y,Clearsky GHI_y,Solar Zenith Angle_y,Clearsky DHI_cb,Clearsky DNI_cb,Clearsky GHI_cb
0,2009,0,0,0,0,0,0,-1.153846,-1.153846,1010,...,1.449289,0.765293,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
1,2009,0,30,0,0,0,0,-1.076923,-1.153846,1010,...,1.554479,0.560281,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
2,2009,1,0,0,0,0,4,-1.153846,-1.153846,1010,...,1.554188,0.249770,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
3,2009,1,30,0,0,0,4,-1.153846,-1.230769,1010,...,1.505634,0.158888,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
4,2009,2,0,0,0,0,4,-1.153846,-1.230769,1010,...,1.423210,-0.059450,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0

In [22]:
print(f"""
Clearsky DHI: {mean_squared_error(Xtrain['Clearsky DHI_x'], Xtrain['Clearsky DHI_cb'])}
Clearsky DNI: {mean_squared_error(Xtrain['Clearsky DNI_x'], Xtrain['Clearsky DNI_cb'])}
Clearsky GHI: {mean_squared_error(Xtrain['Clearsky GHI_x'], Xtrain['Clearsky GHI_cb'])}
"""
)

Clearsky DHI: 25.298290952929165
Clearsky DNI: 220.55004641690047
Clearsky GHI: 7.916533371941885

In [23]:
Xtest['Clearsky DHI_cb'] = Xtest.apply(lambda row: 0 if row['Solar Zenith Angle_x']>=93 or row['Hour_x'] in [1,2,3,4,5,6,7,8,9] else row['Clearsky DHI_cb'], axis=1)
Xtest['Clearsky DNI_cb'] = Xtest.apply(lambda row: 0 if row['Solar Zenith Angle_x']>=93 or row['Hour_x'] in [1,2,3,4,5,6,7,8,9] else row['Clearsky DNI_cb'], axis=1)
Xtest['Clearsky GHI_cb'] = Xtest.apply(lambda row: 0 if row['Solar Zenith Angle_x']>=93 or row['Hour_x'] in [1,2,3,4,5,6,7,8,9] else row['Clearsky GHI_cb'], axis=1)

Xtest['Clearsky DNI_cb'] = Xtest.apply(lambda row: 0 if row['Clearsky DHI_cb']==0 else row['Clearsky DNI_cb'], axis=1)
Xtest['Clearsky GHI_cb'] = Xtest.apply(lambda row: 0 if row['Clearsky DHI_cb']==0 else row['Clearsky GHI_cb'], axis=1)

Xtest.head()

,Year,Hour_x,Minute,Cloud Type,Dew Point,Temperature,Pressure,Relative Humidity,Solar Zenith Angle_x,Precipitable Water,...,Humidity * Wind-72abs_shift,Humidity * Wind+72abs_shift,Hour_y,Solar Zenith Angle_y,Clearsky DHI_y,Clearsky DNI_y,Clearsky GHI_y,Clearsky DHI_cb,Clearsky DNI_cb,Clearsky GHI_cb
0,2019,0,0,7,0.261538,-0.092308,1008,0.416255,106.23,0.235775,...,1.394427,1.024810,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
1,2019,0,30,3,0.261538,-0.107692,1008,0.453956,112.36,0.235775,...,1.534560,1.117081,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
2,2019,1,0,3,0.246154,-0.115385,1008,0.436341,118.58,0.235775,...,1.708750,1.161952,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
3,2019,1,30,3,0.246154,-0.130769,1008,0.474351,124.86,0.235775,...,1.853660,1.214503,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
4,2019,2,0,0,0.230769,-0.153846,1008,0.478368,131.20,0.272964,...,1.917933,1.204656,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0

In [24]:
Xtrain.to_pickle('./train_cb.pkl', compression='gzip')
Xtest.to_pickle('./test_cb.pkl', compression='gzip')

## Create submission file

In [25]:
submission = pd.read_csv("../input/mh-wsmlc/sample_submission.csv")
submission['Clearsky DHI'] = Xtest['Clearsky DHI_cb']
submission['Clearsky DNI'] = Xtest['Clearsky DNI_cb']
submission['Clearsky GHI'] = Xtest['Clearsky GHI_cb']
submission.to_csv("./cb_submission.csv", index=False)
submission.head()

   Clearsky DHI  Clearsky DNI  Clearsky GHI
0           0.0           0.0           0.0
1           0.0           0.0           0.0
2           0.0           0.0           0.0
3           0.0           0.0           0.0
4           0.0           0.0           0.0